const teams = [
    [
        {   "id": 1,
            "games": 26,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2993,
            "fgm": 1084,
            "fga": 2347,
            "fgp": "62.5",
            "ftm": 461,
            "fta": 591,
            "ftp": "78.6",
            "tpm": 328,
            "tpa": 952,
            "tpp": "34.2",
            "offReb": 314,
            "defReb": 845,
            "totReb": 1159,
            "assists": 760,
            "pFouls": 487,
            "steals": 258,
            "turnovers": 435,
            "blocks": 130,
            "plusMinus": -84
        }
    ],
    [
        {   "id":2,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2991,
            "fgm": 1033,
            "fga": 2277,
            "fgp": "61.7",
            "ftm": 451,
            "fta": 554,
            "ftp": "81.1",
            "tpm": 474,
            "tpa": 1284,
            "tpp": "37.1",
            "offReb": 265,
            "defReb": 825,
            "totReb": 1090,
            "assists": 644,
            "pFouls": 441,
            "steals": 195,
            "turnovers": 297,
            "blocks": 136,
            "plusMinus": 249
        }
    ],
    [
        {   "id": 4,
            "games": 26,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2874,
            "fgm": 984,
            "fga": 2158,
            "fgp": "64.6",
            "ftm": 453,
            "fta": 571,
            "ftp": "80.1",
            "tpm": 384,
            "tpa": 1023,
            "tpp": "37.4",
            "offReb": 225,
            "defReb": 757,
            "totReb": 982,
            "assists": 667,
            "pFouls": 577,
            "steals": 178,
            "turnovers": 381,
            "blocks": 97,
            "plusMinus": -90
        }
    ],
    [
        {   "id": 5,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2710,
            "fgm": 973,
            "fga": 2273,
            "fgp": "58.8",
            "ftm": 356,
            "fta": 462,
            "ftp": "75.6",
            "tpm": 408,
            "tpa": 1117,
            "tpp": "36.6",
            "offReb": 326,
            "defReb": 835,
            "totReb": 1161,
            "assists": 576,
            "pFouls": 540,
            "steals": 199,
            "turnovers": 435,
            "blocks": 135,
            "plusMinus": -77
        }
    ],
    [
        {   "id": 6,
            "games": 26,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 3117,
            "fgm": 1094,
            "fga": 2325,
            "fgp": "57.8",
            "ftm": 402,
            "fta": 508,
            "ftp": "76.3",
            "tpm": 416,
            "tpa": 1098,
            "tpp": "36.5",
            "offReb": 235,
            "defReb": 911,
            "totReb": 1146,
            "assists": 726,
            "pFouls": 472,
            "steals": 189,
            "turnovers": 383,
            "blocks": 125,
            "plusMinus": -90
        }
    ],
    [
        {   "id": 7,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 3020,
            "fgm": 1115,
            "fga": 2240,
            "fgp": "63.1",
            "ftm": 422,
            "fta": 543,
            "ftp": "77.2",
            "tpm": 368,
            "tpa": 955,
            "tpp": "38.8",
            "offReb": 231,
            "defReb": 864,
            "totReb": 1095,
            "assists": 700,
            "pFouls": 458,
            "steals": 226,
            "turnovers": 345,
            "blocks": 126,
            "plusMinus": 166
        }
    ],
    [
        {   
            "id": 8,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2899,
            "fgm": 1077,
            "fga": 2239,
            "fgp": "60.4",
            "ftm": 432,
            "fta": 562,
            "ftp": "76.5",
            "tpm": 313,
            "tpa": 864,
            "tpp": "36.2",
            "offReb": 273,
            "defReb": 843,
            "totReb": 1116,
            "assists": 635,
            "pFouls": 515,
            "steals": 214,
            "turnovers": 357,
            "blocks": 138,
            "plusMinus": 137
        }
    ],
    [
        {   
            "id": 9,
            "games": 23,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2671,
            "fgm": 971,
            "fga": 2027,
            "fgp": "60.8",
            "ftm": 449,
            "fta": 604,
            "ftp": "73.8",
            "tpm": 280,
            "tpa": 742,
            "tpp": "38.6",
            "offReb": 258,
            "defReb": 770,
            "totReb": 1028,
            "assists": 687,
            "pFouls": 445,
            "steals": 189,
            "turnovers": 354,
            "blocks": 101,
            "plusMinus": -29
        }
    ],
    [
        {   
            "id": 10,
            "games": 27,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2943,
            "fgm": 1089,
            "fga": 2371,
            "fgp": "62.6",
            "ftm": 426,
            "fta": 554,
            "ftp": "76.0",
            "tpm": 338,
            "tpa": 977,
            "tpp": "34.5",
            "offReb": 300,
            "defReb": 934,
            "totReb": 1234,
            "assists": 702,
            "pFouls": 542,
            "steals": 184,
            "turnovers": 443,
            "blocks": 150,
            "plusMinus": 0
        }
    ],
    [
        {
            "id": 11,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2882,
            "fgm": 1051,
            "fga": 2284,
            "fgp": "65.7",
            "ftm": 382,
            "fta": 532,
            "ftp": "71.8",
            "tpm": 398,
            "tpa": 1055,
            "tpp": "37.7",
            "offReb": 311,
            "defReb": 895,
            "totReb": 1206,
            "assists": 748,
            "pFouls": 526,
            "steals": 225,
            "turnovers": 378,
            "blocks": 141,
            "plusMinus": 224
        }
    ],
    [
        {
            "id": 14,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2888,
            "fgm": 1054,
            "fga": 2371,
            "fgp": "59.6",
            "ftm": 479,
            "fta": 636,
            "ftp": "75.8",
            "tpm": 301,
            "tpa": 913,
            "tpp": "32.5",
            "offReb": 354,
            "defReb": 905,
            "totReb": 1259,
            "assists": 588,
            "pFouls": 520,
            "steals": 225,
            "turnovers": 349,
            "blocks": 141,
            "plusMinus": 215
        }
    ],
    [
        {   
            "id": 15,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2904,
            "fgm": 1082,
            "fga": 2212,
            "fgp": "64.1",
            "ftm": 426,
            "fta": 555,
            "ftp": "77.3",
            "tpm": 314,
            "tpa": 850,
            "tpp": "36.7",
            "offReb": 236,
            "defReb": 789,
            "totReb": 1025,
            "assists": 698,
            "pFouls": 509,
            "steals": 223,
            "turnovers": 378,
            "blocks": 123,
            "plusMinus": -78
        }
    ],
    [
        {
            "id": 16,
            "games": 27,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2933,
            "fgm": 1058,
            "fga": 2265,
            "fgp": "58.9",
            "ftm": 463,
            "fta": 606,
            "ftp": "76.7",
            "tpm": 316,
            "tpa": 871,
            "tpp": "36.4",
            "offReb": 298,
            "defReb": 905,
            "totReb": 1203,
            "assists": 667,
            "pFouls": 506,
            "steals": 273,
            "turnovers": 456,
            "blocks": 126,
            "plusMinus": 96
        }
    ],
    [
        {   
            "id": 17,
            "games": 27,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2986,
            "fgm": 1087,
            "fga": 2355,
            "fgp": "63.6",
            "ftm": 496,
            "fta": 636,
            "ftp": "78.1",
            "tpm": 316,
            "tpa": 939,
            "tpp": "33.7",
            "offReb": 262,
            "defReb": 874,
            "totReb": 1136,
            "assists": 701,
            "pFouls": 441,
            "steals": 204,
            "turnovers": 376,
            "blocks": 132,
            "plusMinus": -135
        }
    ],
    [
        {
            "id": 19,
            "games": 26,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 3123,
            "fgm": 1138,
            "fga": 2368,
            "fgp": "58.3",
            "ftm": 499,
            "fta": 654,
            "ftp": "76.7",
            "tpm": 348,
            "tpa": 988,
            "tpp": "35.3",
            "offReb": 333,
            "defReb": 919,
            "totReb": 1252,
            "assists": 793,
            "pFouls": 564,
            "steals": 223,
            "turnovers": 456,
            "blocks": 177,
            "plusMinus": 166
        }
    ],
    [
        {
            "id": 20,
            "games": 24,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2655,
            "fgm": 943,
            "fga": 2129,
            "fgp": "62.2",
            "ftm": 425,
            "fta": 554,
            "ftp": "77.3",
            "tpm": 344,
            "tpa": 951,
            "tpp": "36.2",
            "offReb": 242,
            "defReb": 790,
            "totReb": 1032,
            "assists": 632,
            "pFouls": 421,
            "steals": 250,
            "turnovers": 320,
            "blocks": 89,
            "plusMinus": 21
        }
    ],
    [
        {
            "id": 21,
            "games": 22,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2426,
            "fgm": 891,
            "fga": 1901,
            "fgp": "62.9",
            "ftm": 332,
            "fta": 455,
            "ftp": "71.3",
            "tpm": 312,
            "tpa": 812,
            "tpp": "38.6",
            "offReb": 190,
            "defReb": 772,
            "totReb": 962,
            "assists": 535,
            "pFouls": 413,
            "steals": 159,
            "turnovers": 319,
            "blocks": 133,
            "plusMinus": -46
        }
    ],
    [
        {
            "id": 22,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2825,
            "fgm": 1008,
            "fga": 2173,
            "fgp": "64.5",
            "ftm": 428,
            "fta": 547,
            "ftp": "79.4",
            "tpm": 381,
            "tpa": 1028,
            "tpp": "37.0",
            "offReb": 249,
            "defReb": 821,
            "totReb": 1070,
            "assists": 627,
            "pFouls": 504,
            "steals": 206,
            "turnovers": 397,
            "blocks": 110,
            "plusMinus": 59
        }
    ],
    [
        {
            "id": 23,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2576,
            "fgm": 915,
            "fga": 2124,
            "fgp": "60.6",
            "ftm": 374,
            "fta": 499,
            "ftp": "72.0",
            "tpm": 249,
            "tpa": 794,
            "tpp": "30.3",
            "offReb": 309,
            "defReb": 738,
            "totReb": 1047,
            "assists": 561,
            "pFouls": 426,
            "steals": 210,
            "turnovers": 377,
            "blocks": 129,
            "plusMinus": -300
        }
    ],
    [
        {
            "id": 24,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2927,
            "fgm": 1074,
            "fga": 2221,
            "fgp": "64.2",
            "ftm": 431,
            "fta": 520,
            "ftp": "82.5",
            "tpm": 348,
            "tpa": 932,
            "tpp": "37.0",
            "offReb": 249,
            "defReb": 840,
            "totReb": 1089,
            "assists": 673,
            "pFouls": 443,
            "steals": 187,
            "turnovers": 316,
            "blocks": 104,
            "plusMinus": 162
        }
    ],
    [
        {
            "id": 25,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2850,
            "fgm": 1064,
            "fga": 2300,
            "fgp": "57.9",
            "ftm": 379,
            "fta": 488,
            "ftp": "77.3",
            "tpm": 343,
            "tpa": 992,
            "tpp": "34.6",
            "offReb": 250,
            "defReb": 850,
            "totReb": 1100,
            "assists": 648,
            "pFouls": 522,
            "steals": 288,
            "turnovers": 302,
            "blocks": 163,
            "plusMinus": 259
        }
    ],
    [
        {
            "id": 26,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2692,
            "fgm": 958,
            "fga": 2125,
            "fgp": "63.6",
            "ftm": 478,
            "fta": 609,
            "ftp": "78.6",
            "tpm": 298,
            "tpa": 948,
            "tpp": "31.4",
            "offReb": 262,
            "defReb": 809,
            "totReb": 1071,
            "assists": 620,
            "pFouls": 506,
            "steals": 237,
            "turnovers": 387,
            "blocks": 171,
            "plusMinus": 130
        }
    ],
    [
        {
            "id": 27,
            "games": 22,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2323,
            "fgm": 807,
            "fga": 1867,
            "fgp": "64.7",
            "ftm": 410,
            "fta": 528,
            "ftp": "78.0",
            "tpm": 258,
            "tpa": 797,
            "tpp": "32.1",
            "offReb": 245,
            "defReb": 654,
            "totReb": 899,
            "assists": 452,
            "pFouls": 449,
            "steals": 205,
            "turnovers": 323,
            "blocks": 96,
            "plusMinus": -114
        }
    ],
    [
        {
            "id": 28,
            "games": 24,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2704,
            "fgm": 963,
            "fga": 2089,
            "fgp": "60.8",
            "ftm": 408,
            "fta": 526,
            "ftp": "77.8",
            "tpm": 363,
            "tpa": 978,
            "tpp": "37.4",
            "offReb": 216,
            "defReb": 833,
            "totReb": 1049,
            "assists": 653,
            "pFouls": 437,
            "steals": 185,
            "turnovers": 341,
            "blocks": 127,
            "plusMinus": -22
        }
    ],
    [
        {
            "id": 29,
            "games": 24,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2580,
            "fgm": 927,
            "fga": 2135,
            "fgp": "62.1",
            "ftm": 408,
            "fta": 534,
            "ftp": "76.8",
            "tpm": 281,
            "tpa": 831,
            "tpp": "34.2",
            "offReb": 319,
            "defReb": 732,
            "totReb": 1051,
            "assists": 535,
            "pFouls": 471,
            "steals": 223,
            "turnovers": 404,
            "blocks": 147,
            "plusMinus": -100
        }
    ],
    [
        {
            "id": 30,
            "games": 26,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2907,
            "fgm": 1077,
            "fga": 2298,
            "fgp": "66.1",
            "ftm": 464,
            "fta": 591,
            "ftp": "78.6",
            "tpm": 289,
            "tpa": 915,
            "tpp": "31.4",
            "offReb": 281,
            "defReb": 855,
            "totReb": 1136,
            "assists": 651,
            "pFouls": 546,
            "steals": 230,
            "turnovers": 386,
            "blocks": 114,
            "plusMinus": -53
        }
    ],
    [
        {
            "id": 31,
            "games": 25,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2786,
            "fgm": 1000,
            "fga": 2154,
            "fgp": "58.6",
            "ftm": 435,
            "fta": 555,
            "ftp": "79.5",
            "tpm": 351,
            "tpa": 993,
            "tpp": "35.1",
            "offReb": 257,
            "defReb": 840,
            "totReb": 1097,
            "assists": 714,
            "pFouls": 422,
            "steals": 198,
            "turnovers": 385,
            "blocks": 152,
            "plusMinus": -7
        }
    ],
    [
        {   
            "id": 38,
            "games": 26,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2934,
            "fgm": 1110,
            "fga": 2376,
            "fgp": "64.9",
            "ftm": 427,
            "fta": 584,
            "ftp": "72.7",
            "tpm": 287,
            "tpa": 846,
            "tpp": "33.9",
            "offReb": 357,
            "defReb": 860,
            "totReb": 1217,
            "assists": 759,
            "pFouls": 606,
            "steals": 203,
            "turnovers": 433,
            "blocks": 116,
            "plusMinus": -74
        }
    ],
    [
        {
            "id": 40,
            "games": 26,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2835,
            "fgm": 994,
            "fga": 2202,
            "fgp": "60.6",
            "ftm": 516,
            "fta": 656,
            "ftp": "78.7",
            "tpm": 331,
            "tpa": 962,
            "tpp": "34.9",
            "offReb": 312,
            "defReb": 852,
            "totReb": 1164,
            "assists": 619,
            "pFouls": 485,
            "steals": 188,
            "turnovers": 495,
            "blocks": 134,
            "plusMinus": -188
        }
    ],
    [
        {
            "id": 41,
            "games": 23,
            "fastBreakPoints": 0,
            "pointsInPaint": 0,
            "biggestLead": 0,
            "secondChancePoints": 0,
            "pointsOffTurnovers": 0,
            "longestRun": 0,
            "points": 2461,
            "fgm": 883,
            "fga": 1988,
            "fgp": "63.4",
            "ftm": 382,
            "fta": 502,
            "ftp": "75.9",
            "tpm": 268,
            "tpa": 819,
            "tpp": "32.4",
            "offReb": 202,
            "defReb": 737,
            "totReb": 939,
            "assists": 551,
            "pFouls": 505,
            "steals": 175,
            "turnovers": 380,
            "blocks": 123,
            "plusMinus": -340
        }
    ]
]


module.exports = teams